DEFAULT_PROC_NAME = "FIFA21.exe"

URL_LINKS = {
    PATREON = "https://www.patreon.com/xAranaktu",
    DISCORD = "https://discord.gg/va9EtdB",
    VERSION = "https://raw.githubusercontent.com/xAranaktu/FIFA-21-CM-Cheat-Table/master/VERSION"
}

CT_MEMORY_RECORDS = {
    GUI_SCRIPT = 15,
    PLAYERS_SECONDARY_POS = 43,
    PLAYERS_PRIMARY_POS = 47,
    PLAYERS_NATIONALITY = 88,

    NO_YES_CB = 132,
    FIVE_STARS_CB = 102,
    WR_CB = 86,
    GENDER_CB = 58,
    PREFERREDFOOT_CB = 89
}

AOB_PATTERNS = {
    DisablePGM = "85 C0 0F 95 85 60 05 00 00",

    ScreenID = '48 8D 35 ?? ?? ?? ?? 48 0F 45 35 ?? ?? ?? ?? 49 8B FF',
    DatabaseRead = '48 ?? ?? 4C 03 46 30 E8',
    DatabaseBasePtr = "4C 0F 44 35 ?? ?? ?? ?? 41 8B 4E 08",
    SideManipulator = "48 8B 84 CF 20 01 00 00 83",
    GTNRevealPlayerData = "8B 8D 9C 02 00 00 39",
    OnSharpnessChange = "41 88 71 24 48 8B 5C 24 50",
    OnStaminaChange1 = "0F BE C2 88 51 11",
    OnStaminaChange2 = "88 43 11 0F B6 47 0D",
    HireScout = "41 8B 01 89 45 38",
    UnlimitedSubstitutions = "8B 84 01 EC 9B 00 00",

    AgreeTransferRequest = "44 8B E8 48 8B 89 98 01 00 00",
    AltTab = "48 83 ec 48 48 83 3d ?? ?? ?? ?? ?? 74"
}

DEFAULT_CFG = {
    flags = {
        debug_mode = false,
        deactive_on_close = false,
        hide_ce_scanner = false,
        check_for_update = true,
        only_check_for_free_update = false,
        cache_players_data = false,
        hide_players_potential = false
    },
    directories = {
    },
    game =
    {
        name = DEFAULT_PROC_NAME,
        name_trial = "FIFA21_TRIAL.exe"
    },
    gui = {
        opacity = 255
    },
    auto_activate = {
        18,      -- Scripts
        214      -- FIFA Database Tables
    },
    hotkeys = {
        sync_with_game = 'VK_F5',
        search_player_by_id = 'VK_RETURN'
    },
    theme = {
        default = 'dark',
        current = 'dark'
    },
    language = {
        default = 'en_US',
        current = 'en_US'
    },
    other = {
        ignore_update = "21.1.0.0"
    }
}

DB_TABLE_STRUCT_OFFSETS = {
    first_record = 0x30,                -- 8 bytes
    shortname = 0x40,                   -- 4 bytes
    record_size = 0x44,                 -- 4 bytes
    bit_records_count = 0x48,           -- 4 bytes
    compressed_str_len = 0x50,          -- 4 bytes
    total_records = 0x78,               -- 2 bytes
    total_records2 = 0x7A,              -- 2 bytes
    written_records = 0x7C,             -- 2 bytes
    canceled_records = 0x7E,            -- 2 bytes
    fieldcount = 0x82                   -- 1 bytes
}

DB_TABLES_META_MAP = {
    teamplayerlinks = {
        artificialkey = 1,
        teamid = 2,
        isamongtopscorers = 3,
        istopscorer = 4,
        form = 5,
        reds = 6,
        leagueappearances = 7,
        jerseynumber = 8,
        leaguegoalsprevmatch = 9,
        leaguegoals = 10,
        playerid = 11,
        injury = 12,
        leaguegoalsprevthreematches = 13,
        yellows = 14,
        isamongtopscorersinteam = 15,
        position = 16
    },
    players = {
        playerid = 1,
        weakfootabilitytypecode = 2,
        accessorycolourcode4 = 3,
        accessorycode1 = 4,
        personality = 5,
        smallsidedshoetypecode = 6,
        modifier = 7,
        animfreekickstartposcode = 8,
        gkkicking = 9,
        jerseyfit = 10,
        jerseystylecode = 11,
        dribbling = 12,
        shotpower = 13,
        balance = 14,
        headvariation = 15,
        contractvaliduntil = 16,
        firstnameid = 17,
        haircolorcode = 18,
        marking = 19,
        preferredposition1 = 20,
        hashighqualityhead = 21,
        penalties = 22,
        volleys = 23,
        tattooback = 24,
        headclasscode = 25,
        tattoorightleg = 26,
        finishingcode2 = 27,
        iscustomized = 28,
        slidingtackle = 29,
        animpenaltieskickstylecode = 30,
        jumping = 31,
        birthdate = 32,
        runningcode1 = 33,
        headingaccuracy = 34,
        aggression = 35,
        trait1 = 36,
        longpassing = 37,
        potential = 38,
        socklengthcode = 39,
        weight = 40,
        shoetypecode = 41,
        bodytypecode = 42,
        gkpositioning = 43,
        skintypecode = 44,
        gkglovetypecode = 45,
        tattooleftarm = 46,
        lastnameid = 47,
        preferredposition4 = 48,
        curve = 49,
        nationality = 50,
        skintonecode = 51,
        animpenaltiesapproachcode = 52,
        isretiring = 53,
        accessorycolourcode1 = 54,
        facialhaircolorcode = 55,
        sideburnscode = 56,
        animpenaltiesstartposcode = 57,
        shoecolorcode2 = 58,
        strength = 59,
        accessorycode4 = 60,
        faceposerpreset = 61,
        playerjointeamdate = 62,
        shortpassing = 63,
        interceptions = 64,
        finishing = 65,
        attackingworkrate = 66,
        hairtypecode = 67,
        gender = 68,
        gkhandling = 69,
        sprintspeed = 70,
        preferredposition2 = 71,
        acceleration = 72,
        stamina = 73,
        reactions = 74,
        eyecolorcode = 75,
        accessorycolourcode3 = 76,
        defensiveworkrate = 77,
        accessorycode2 = 78,
        emotion = 79,
        hasseasonaljersey = 80,
        trait2 = 81,
        runningcode2 = 82,
        facialhairtypecode = 83,
        crossing = 84,
        gkdiving = 85,
        height = 86,
        skillmoves = 87,
        longshots = 88,
        tattooleftleg = 89,
        standingtackle = 90,
        finishingcode1 = 91,
        eyebrowcode = 92,
        commonnameid = 93,
        usercaneditname = 94,
        tattoofront = 95,
        shoedesigncode = 96,
        skillmoveslikelihood = 97,
        agility = 98,
        gksavetype = 99,
        avatarpomid = 100,
        freekickaccuracy = 101,
        playerjerseynameid = 102,
        internationalrep = 103,
        positioning = 104,
        tattoorightarm = 105,
        vision = 106,
        gkreflexes = 107,
        composure = 108,
        animpenaltiesmotionstylecode = 109,
        gkkickstyle = 110,
        shortstyle = 111,
        accessorycode3 = 112,
        tattoohead = 113,
        accessorycolourcode2 = 114,
        shoecolorcode1 = 115,
        headassetid = 116,
        ballcontrol = 117,
        preferredfoot = 118,
        headtypecode = 119,
        hairstylecode = 120,
        preferredposition3 = 121,
        runstylecode = 122,
        overallrating = 123,
        jerseysleevelengthcode = 124
    }
}


DB_TABLES_META = {
    teamplayerlinks = {
        {
            name = "artificialkey",
            shortname = "JMld",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 19,
            offset = 0x3,
            rangehigh = 300000,
            rangelow = 0,
            startbit = 5,
            key = true,
        },
        {
            name = "teamid",
            shortname = "mCXg",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 18,
            offset = 0x6,
            rangehigh = 200000,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "isamongtopscorers",
            shortname = "SuuG",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x1,
            rangehigh = 1,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "istopscorer",
            shortname = "YbEm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0xA,
            rangehigh = 1,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "form",
            shortname = "rLZx",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0xD,
            rangehigh = 5,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "reds",
            shortname = "jIcz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0xD,
            rangehigh = 20,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "leagueappearances",
            shortname = "stFk",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x9,
            rangehigh = 50,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "jerseynumber",
            shortname = "JFiY",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x2,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "leaguegoalsprevmatch",
            shortname = "NbFh",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x8,
            rangehigh = 10,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "leaguegoals",
            shortname = "UMDX",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 8,
            offset = 0x0,
            rangehigh = 200,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "playerid",
            shortname = "ykFq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 19,
            offset = 0xB,
            rangehigh = 500000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "injury",
            shortname = "Vili",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x8,
            rangehigh = 35,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "leaguegoalsprevthreematches",
            shortname = "dGNm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0xA,
            rangehigh = 25,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "yellows",
            shortname = "jtWI",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x1,
            rangehigh = 40,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "isamongtopscorersinteam",
            shortname = "pchV",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x1,
            rangehigh = 1,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "position",
            shortname = "vjla",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x2,
            rangehigh = 33,
            rangelow = 0,
            startbit = 7,
        },
    },
    players = {
        {
            name = "playerid",
            shortname = "ykFq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 19,
            offset = 0x5A,
            rangehigh = 500000,
            rangelow = 0,
            startbit = 7,
            key = true,
        },
        {
            name = "weakfootabilitytypecode",
            shortname = "aOBn",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x58,
            rangehigh = 5,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "accessorycolourcode4",
            shortname = "cAUq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x5E,
            rangehigh = 13,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "accessorycode1",
            shortname = "gOol",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x51,
            rangehigh = 27,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "personality",
            shortname = "hxxo",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x59,
            rangehigh = 5,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "smallsidedshoetypecode",
            shortname = "iKqs",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x62,
            rangehigh = 1000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "modifier",
            shortname = "isYi",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x4E,
            rangehigh = 5,
            rangelow = -5,
            startbit = 5,
        },
        {
            name = "animfreekickstartposcode",
            shortname = "jLuE",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x17,
            rangehigh = 9,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "gkkicking",
            shortname = "kqda",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x41,
            rangehigh = 99,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "jerseyfit",
            shortname = "lTKv",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x64,
            rangehigh = 2,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "jerseystylecode",
            shortname = "miIB",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0xE,
            rangehigh = 1,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "dribbling",
            shortname = "nEbM",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x25,
            rangehigh = 99,
            rangelow = 1,
            startbit = 6,
        },
        {
            name = "shotpower",
            shortname = "ohpV",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x35,
            rangehigh = 99,
            rangelow = 1,
            startbit = 7,
        },
        {
            name = "balance",
            shortname = "onkY",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x3E,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "headvariation",
            shortname = "pHkq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x5F,
            rangehigh = 31,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "contractvaliduntil",
            shortname = "qvmK",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 11,
            offset = 0x23,
            rangehigh = 2047,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "firstnameid",
            shortname = "tHlO",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 16,
            offset = 0x0,
            rangehigh = 50000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "haircolorcode",
            shortname = "uGEA",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0xC,
            rangehigh = 15,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "marking",
            shortname = "wxMq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x5D,
            rangehigh = 99,
            rangelow = 1,
            startbit = 2,
        },
        {
            name = "preferredposition1",
            shortname = "wZQU",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x33,
            rangehigh = 31,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "hashighqualityhead",
            shortname = "ykrW",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x3B,
            rangehigh = 1,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "penalties",
            shortname = "AGsE",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x16,
            rangehigh = 99,
            rangelow = 1,
            startbit = 7,
        },
        {
            name = "volleys",
            shortname = "Dydz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x6B,
            rangehigh = 99,
            rangelow = 1,
            startbit = 2,
        },
        {
            name = "tattooback",
            shortname = "HEDC",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0xF,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "headclasscode",
            shortname = "HvCm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x54,
            rangehigh = 2,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "tattoorightleg",
            shortname = "JRjz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x6C,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "finishingcode2",
            shortname = "LwOe",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 17,
            offset = 0x47,
            rangehigh = 100000,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "iscustomized",
            shortname = "Oirg",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x4B,
            rangehigh = 1,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "slidingtackle",
            shortname = "PhuM",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x26,
            rangehigh = 99,
            rangelow = 1,
            startbit = 5,
        },
        {
            name = "animpenaltieskickstylecode",
            shortname = "SAHF",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x18,
            rangehigh = 2,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "jumping",
            shortname = "URGo",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x58,
            rangehigh = 99,
            rangelow = 1,
            startbit = 4,
        },
        {
            name = "birthdate",
            shortname = "WVIU",
            fld_type = "DBOFIELDTYPE_DATE",
            depth = 20,
            offset = 0x30,
            rangehigh = 1048575,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "runningcode1",
            shortname = "ZeVz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 17,
            offset = 0x68,
            rangehigh = 100000,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "headingaccuracy",
            shortname = "aReg",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x4B,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "aggression",
            shortname = "iTce",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x49,
            rangehigh = 99,
            rangelow = 1,
            startbit = 2,
        },
        {
            name = "trait1",
            shortname = "juxV",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 30,
            offset = 0x36,
            rangehigh = 1073741823,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "longpassing",
            shortname = "kerE",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x16,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "potential",
            shortname = "mpuH",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x1C,
            rangehigh = 99,
            rangelow = 1,
            startbit = 6,
        },
        {
            name = "socklengthcode",
            shortname = "nVWW",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x3A,
            rangehigh = 4,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "weight",
            shortname = "sNZW",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x3A,
            rangehigh = 150,
            rangelow = 30,
            startbit = 7,
        },
        {
            name = "shoetypecode",
            shortname = "tgwT",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x2F,
            rangehigh = 1000,
            rangelow = 0,
            startbit = 3,
        },
        {
            name = "bodytypecode",
            shortname = "xWyx",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 9,
            offset = 0x66,
            rangehigh = 512,
            rangelow = 1,
            startbit = 6,
        },
        {
            name = "gkpositioning",
            shortname = "yfhq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x5E,
            rangehigh = 99,
            rangelow = 1,
            startbit = 5,
        },
        {
            name = "skintypecode",
            shortname = "Dlgo",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 8,
            offset = 0x8,
            rangehigh = 160,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "gkglovetypecode",
            shortname = "GReX",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x3B,
            rangehigh = 127,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "tattooleftarm",
            shortname = "HfYD",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x11,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "lastnameid",
            shortname = "QCfa",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 16,
            offset = 0x2,
            rangehigh = 50000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "preferredposition4",
            shortname = "YnYz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x6A,
            rangehigh = 32,
            rangelow = -1,
            startbit = 4,
        },
        {
            name = "curve",
            shortname = "YFaA",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0xD,
            rangehigh = 99,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "nationality",
            shortname = "enmm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 12,
            offset = 0x56,
            rangehigh = 3000,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "skintonecode",
            shortname = "ejir",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x60,
            rangehigh = 11,
            rangelow = 1,
            startbit = 4,
        },
        {
            name = "animpenaltiesapproachcode",
            shortname = "fmxK",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x24,
            rangehigh = 2,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "isretiring",
            shortname = "kvuF",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x18,
            rangehigh = 1,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "accessorycolourcode1",
            shortname = "kmkN",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x28,
            rangehigh = 13,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "facialhaircolorcode",
            shortname = "mIlz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x6D,
            rangehigh = 11,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "sideburnscode",
            shortname = "mrAn",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x57,
            rangehigh = 3,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "animpenaltiesstartposcode",
            shortname = "naby",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x67,
            rangehigh = 8,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "shoecolorcode2",
            shortname = "nbJH",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x1B,
            rangehigh = 31,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "strength",
            shortname = "nmgT",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x2E,
            rangehigh = 99,
            rangelow = 1,
            startbit = 4,
        },
        {
            name = "accessorycode4",
            shortname = "oQQC",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x10,
            rangehigh = 27,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "faceposerpreset",
            shortname = "qwYd",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x45,
            rangehigh = 15,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "playerjointeamdate",
            shortname = "vTpl",
            fld_type = "DBOFIELDTYPE_DATE",
            depth = 20,
            offset = 0x52,
            rangehigh = 1048575,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "shortpassing",
            shortname = "vObb",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x43,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "interceptions",
            shortname = "wWzG",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x1A,
            rangehigh = 99,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "finishing",
            shortname = "xJZL",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x24,
            rangehigh = 99,
            rangelow = 1,
            startbit = 7,
        },
        {
            name = "attackingworkrate",
            shortname = "BqFe",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x46,
            rangehigh = 2,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "hairtypecode",
            shortname = "CkYD",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x13,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "gender",
            shortname = "EveZ",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x3E,
            rangehigh = 1,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "gkhandling",
            shortname = "GBGj",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x4F,
            rangehigh = 99,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "sprintspeed",
            shortname = "NrcP",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x2A,
            rangehigh = 99,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "preferredposition2",
            shortname = "NgVS",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x2D,
            rangehigh = 32,
            rangelow = -1,
            startbit = 6,
        },
        {
            name = "acceleration",
            shortname = "SPge",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x4A,
            rangehigh = 99,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "stamina",
            shortname = "XjDq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x5A,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "reactions",
            shortname = "YCnI",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x20,
            rangehigh = 99,
            rangelow = 1,
            startbit = 5,
        },
        {
            name = "eyecolorcode",
            shortname = "Zufj",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x50,
            rangehigh = 16,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "accessorycolourcode3",
            shortname = "acRl",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x50,
            rangehigh = 13,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "defensiveworkrate",
            shortname = "boFm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x54,
            rangehigh = 2,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "accessorycode2",
            shortname = "dXNv",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x64,
            rangehigh = 27,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "emotion",
            shortname = "gNbt",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x63,
            rangehigh = 5,
            rangelow = 1,
            startbit = 2,
        },
        {
            name = "hasseasonaljersey",
            shortname = "iCDR",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x2C,
            rangehigh = 7,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "trait2",
            shortname = "inAr",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 24,
            offset = 0x9,
            rangehigh = 16777215,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "runningcode2",
            shortname = "oXYh",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 17,
            offset = 0x4C,
            rangehigh = 100000,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "facialhairtypecode",
            shortname = "onGA",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0xC,
            rangehigh = 19,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "crossing",
            shortname = "wGOH",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x1B,
            rangehigh = 99,
            rangelow = 1,
            startbit = 7,
        },
        {
            name = "gkdiving",
            shortname = "xrSG",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x19,
            rangehigh = 99,
            rangelow = 1,
            startbit = 4,
        },
        {
            name = "height",
            shortname = "ypBQ",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x2B,
            rangehigh = 220,
            rangelow = 130,
            startbit = 2,
        },
        {
            name = "skillmoves",
            shortname = "BAPc",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x44,
            rangehigh = 4,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "longshots",
            shortname = "CsBG",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x18,
            rangehigh = 99,
            rangelow = 1,
            startbit = 5,
        },
        {
            name = "tattooleftleg",
            shortname = "CVWU",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x33,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "standingtackle",
            shortname = "CsyD",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x14,
            rangehigh = 99,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "finishingcode1",
            shortname = "GFLI",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 17,
            offset = 0x1E,
            rangehigh = 100000,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "eyebrowcode",
            shortname = "HqUh",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x4C,
            rangehigh = 15,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "commonnameid",
            shortname = "HDYx",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 16,
            offset = 0x6,
            rangehigh = 50000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "usercaneditname",
            shortname = "NBsd",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x45,
            rangehigh = 1,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "tattoofront",
            shortname = "OnPm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x55,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "shoedesigncode",
            shortname = "PeUv",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x65,
            rangehigh = 3,
            rangelow = 0,
            startbit = 2,
        },
        {
            name = "skillmoveslikelihood",
            shortname = "PJsq",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x60,
            rangehigh = 4,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "agility",
            shortname = "RRQB",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0xE,
            rangehigh = 99,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "gksavetype",
            shortname = "SJED",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x10,
            rangehigh = 1,
            rangelow = 0,
            startbit = 7,
        },
        {
            name = "avatarpomid",
            shortname = "VRvd",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 9,
            offset = 0x45,
            rangehigh = 511,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "freekickaccuracy",
            shortname = "VgKc",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x43,
            rangehigh = 99,
            rangelow = 1,
            startbit = 7,
        },
        {
            name = "playerjerseynameid",
            shortname = "Vqpv",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 16,
            offset = 0x4,
            rangehigh = 50000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "internationalrep",
            shortname = "WVsa",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x42,
            rangehigh = 5,
            rangelow = 1,
            startbit = 2,
        },
        {
            name = "positioning",
            shortname = "XsFD",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x11,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "tattoorightarm",
            shortname = "YjNY",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x3C,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "vision",
            shortname = "ZoOK",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x22,
            rangehigh = 99,
            rangelow = 1,
            startbit = 3,
        },
        {
            name = "gkreflexes",
            shortname = "eYFI",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x1D,
            rangehigh = 99,
            rangelow = 1,
            startbit = 5,
        },
        {
            name = "composure",
            shortname = "jlQJ",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x21,
            rangehigh = 99,
            rangelow = 1,
            startbit = 4,
        },
        {
            name = "animpenaltiesmotionstylecode",
            shortname = "nRxa",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x42,
            rangehigh = 6,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "gkkickstyle",
            shortname = "rJqp",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 2,
            offset = 0x59,
            rangehigh = 3,
            rangelow = 0,
            startbit = 6,
        },
        {
            name = "shortstyle",
            shortname = "wwlr",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x61,
            rangehigh = 1,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "accessorycode3",
            shortname = "ycJN",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x27,
            rangehigh = 27,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "tattoohead",
            shortname = "BhwR",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 10,
            offset = 0x2C,
            rangehigh = 1023,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "accessorycolourcode2",
            shortname = "Bfhz",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 4,
            offset = 0x6C,
            rangehigh = 13,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "shoecolorcode1",
            shortname = "CSEx",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x65,
            rangehigh = 31,
            rangelow = 0,
            startbit = 4,
        },
        {
            name = "headassetid",
            shortname = "GEba",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 19,
            offset = 0x3F,
            rangehigh = 500000,
            rangelow = 0,
            startbit = 0,
        },
        {
            name = "ballcontrol",
            shortname = "MgwU",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x35,
            rangehigh = 99,
            rangelow = 1,
            startbit = 0,
        },
        {
            name = "preferredfoot",
            shortname = "MDvm",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 1,
            offset = 0x57,
            rangehigh = 2,
            rangelow = 1,
            startbit = 6,
        },
        {
            name = "headtypecode",
            shortname = "OoQO",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 14,
            offset = 0x28,
            rangehigh = 16000,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "hairstylecode",
            shortname = "OFRx",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 5,
            offset = 0x66,
            rangehigh = 31,
            rangelow = 0,
            startbit = 1,
        },
        {
            name = "preferredposition3",
            shortname = "OblE",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x15,
            rangehigh = 32,
            rangelow = -1,
            startbit = 2,
        },
        {
            name = "runstylecode",
            shortname = "Tbvt",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 6,
            offset = 0x63,
            rangehigh = 32,
            rangelow = 0,
            startbit = 5,
        },
        {
            name = "overallrating",
            shortname = "UERs",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 7,
            offset = 0x61,
            rangehigh = 99,
            rangelow = 1,
            startbit = 1,
        },
        {
            name = "jerseysleevelengthcode",
            shortname = "UFvj",
            fld_type = "DBOFIELDTYPE_INTEGER",
            depth = 3,
            offset = 0x50,
            rangehigh = 7,
            rangelow = 0,
            startbit = 4,
        }
    }
}

-- All available forms
FORMS = {
    MainWindowForm, SettingsForm, PlayersEditorForm
}